version: '3'
services:
  search:
    image: abadi199/go-search_search:0.0.1
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
    - "8081:8080"
  search_db:
    image: mongo
    ports:
    - "27017:27017"
    volumes:
    - "mongodata:/data/db"
  frontend:
    image: abadi199/go-search_frontend:0.0.1
    ports:
    - "8080:80"
volumes:
  mongodata: