version: '3'
services:
  search:
    build: './search'
    ports:
    - "8081:8080"
  search_db:
    image: mongo
    ports:
    - "27017:27017"
    volumes:
    - "mongodata:/data/db"
  frontend:
    build: './frontend'
    ports:
    - "8080:80"
volumes:
  mongodata: